[build]
  command = "npm run build"
  publish = "dist" # ou "build", dependendo do seu framework

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL"